import { beforeEach, afterEach, describe, it, expect, vi } from "vitest";
import { quantitySchema, publicQuantitySchema, routesSchema, searchSchema, uint64, validatePage, productQuery, reasonText } from "./product-contract";
import { createProductRequestSchema, removeProductRequestSchema, receiveLookupSchema } from "./operator-contract";
import { publicProductGateway, publicSearchGateway } from "./public-gateway";
import { operatorGateway } from "./operator-gateway";
import { createPublicClient } from "./public-client";
import { batchId, batchQuantity, batchPreview, sourceRoutes, firstRoutePage, searchPage, writeResult, ownRoutes } from "../../tests/batch-fixtures";
import { operatorUser } from "../../tests/operator-fixtures";
const token="tfos_"+"A".repeat(43),origin="https://dashboard.example";
const response=(body:unknown,status=200)=>Response.json(body,{status});
const request=(suffix:string,body?:unknown,cookie?:string)=>new Request(origin+suffix,{method:body?"POST":"GET",headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});
beforeEach(()=>{vi.stubEnv("TRACEFORGE_PUBLIC_API_ORIGIN","https://api.example");vi.stubEnv("TRACEFORGE_OPERATOR_SITE_ORIGIN",origin);vi.stubEnv("TRACEFORGE_OPERATOR_API_ORIGIN","https://api.example")});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe("quantity and registration contracts",()=>{
 it("keeps million-item global totals separate from the caller's available stock",()=>{expect(quantitySchema.parse({...batchQuantity,ownAvailableQuantity:"199300"}).availableQuantity).toBe("899300");expect(publicQuantitySchema.safeParse({...batchQuantity,ownAvailableQuantity:"199300"}).success).toBe(false);});
 it("rejects inconsistent balances, reason totals, batch classification and stock status",()=>{
  for(const invalid of [{...batchQuantity,availableQuantity:"899301"},{...batchQuantity,ownAvailableQuantity:"999999"},{...batchQuantity,reasons:batchQuantity.reasons.map(r=>({...r,quantity:"0"}))},{...batchQuantity,isBatch:false},{...batchQuantity,inSupplyChain:false},{...batchQuantity,reasons:batchQuantity.reasons.map(()=>batchQuantity.reasons[0])},{...batchQuantity,initialQuantity:"9007199254740992"},{...batchQuantity,availableQuantity:"bad"},{...batchQuantity,initialQuantity:1000000},{...batchQuantity,secret:"PRIVATE_SENTINEL"}])expect(quantitySchema.safeParse(invalid).success).toBe(false);
 });
 it("keeps a batch classification when only one item remains",()=>{const data={...batchQuantity,availableQuantity:"1",removedQuantity:"999999",reasons:batchQuantity.reasons.map(r=>({...r,quantity:r.reason==="Sold"?"999999":"0"}))};expect(quantitySchema.parse(data).isBatch).toBe(true)});
 it("rejects imprecise input quantities but permits omitted single quantity and duplicate business references",()=>{const base={name:"Product",id:"BATCH-001",publish:false,idempotencyKey:"test-request-1234"};expect(createProductRequestSchema.parse(base).quantity).toBeUndefined();expect(createProductRequestSchema.parse({...base,quantity:1}).id).toBe(base.id);for(const quantity of [null,"2",true,1.5,0,-1,9007199254740992])expect(createProductRequestSchema.safeParse({...base,quantity}).success).toBe(false);});
 it("reserves canonical identity/count fields and rejects invalid Unicode IDs",()=>{const base={name:"Product",id:"BATCH-001",publish:false,idempotencyKey:"test-request-1234"};for(const label of [" id ","QUANTITY","Product / batch ID","schemaVersion","Number of items"])expect(createProductRequestSchema.safeParse({...base,fields:[{label,value:"2"}]}).success).toBe(false);for(const id of ["", "A\x01B","A\ud800B","😀".repeat(121)])expect(createProductRequestSchema.safeParse({...base,id}).success).toBe(false);expect(createProductRequestSchema.parse({...base,id:"😀".repeat(120)}).id).toHaveLength(240)});
 it("requires explanations for every non-Sold reason and preserves on-chain text",()=>{
  const base={version:"1",confirmed:true,idempotencyKey:"test-request-1234"};expect(removeProductRequestSchema.parse(base)).toMatchObject({reason:"Sold",reasonText:""});for(const reason of ["Lost","Damaged","Spoiled","Disposed","Other"]){for(const text of ["","  "])expect(removeProductRequestSchema.safeParse({...base,reason,reasonText:text}).success).toBe(false);expect(removeProductRequestSchema.parse({...base,reason,reasonText:" বাংলাদেশ \n"}).reasonText).toBe(" বাংলাদেশ \n");}
  expect(reasonText.safeParse("😀".repeat(256)).success).toBe(true);for(const text of ["😀".repeat(257),"bad\x00text","bad\ud800text"])expect(reasonText.safeParse(text).success).toBe(false);
 });
 it("validates minimal private batch previews without publishing metadata",()=>{const preview={...batchPreview,name:null,quantity:{...batchPreview.quantity,externalId:null}};expect(receiveLookupSchema.parse(preview).name).toBeNull();expect(receiveLookupSchema.safeParse({...preview,document:{secret:true}}).success).toBe(false);expect(receiveLookupSchema.safeParse({...preview,holder:sourceRoutes[0].owner}).success).toBe(false);});
 it("rejects duplicate routes, excess balances and nonadvancing cursors without losing large versions",()=>{expect(routesSchema.parse(firstRoutePage).routes[0].version).toBe("9007199254741001");expect(routesSchema.safeParse({...firstRoutePage,routes:[sourceRoutes[0],sourceRoutes[0]]}).success).toBe(false);expect(routesSchema.safeParse({...firstRoutePage,routes:[{...sourceRoutes[0],availableQuantity:"600001"}]}).success).toBe(false);expect(()=>validatePage(firstRoutePage,"9007199254741010",50,"routes")).toThrow();for(const value of ["1.5","01","-1","18446744073709551616","x".repeat(1000)])expect(uint64.safeParse(value).success).toBe(false);});
});
describe("fixed discovery gateways",()=>{
 it("public search never forwards cookies, authorization or upstream errors and validates exact business IDs",async()=>{
  const spy=vi.fn<typeof fetch>().mockResolvedValue(response(searchPage));vi.stubGlobal("fetch",spy);
  const req=new Request(origin+"/public/v1/products/search?id=A%20%2F%20BATCH-001",{headers:{Cookie:"SECRET",Authorization:"Bearer SECRET"}});const result=await publicSearchGateway(req);expect(result.status).toBe(200);expect(spy.mock.calls[0][1]).toMatchObject({credentials:"omit",cache:"no-store",headers:{Accept:"application/json"}});expect(spy.mock.calls[0][1]?.headers).not.toHaveProperty("Cookie");expect(spy.mock.calls[0][1]?.headers).not.toHaveProperty("Authorization");
  spy.mockResolvedValue(response({...searchPage,products:[{...searchPage.products[0],externalId:"Wrong ID"}]}));expect((await publicSearchGateway(req)).status).toBe(502);
  spy.mockResolvedValue(response({...searchPage,sessionToken:"PRIVATE_SENTINEL"}));const invalid=await publicSearchGateway(req);expect(invalid.status).toBe(502);expect(await invalid.text()).not.toContain("PRIVATE_SENTINEL");
 });
 it("rejects unknown or duplicate queries, oversized pages and malformed identifiers before network access",async()=>{
  const spy=vi.fn<typeof fetch>();vi.stubGlobal("fetch",spy);
  for(const query of ["id=X&id=Y","id=X&url=https://evil.example","id=X&businessCode=BAD-CODE","id=X&limit=101","id=X&after=18446744073709551616","id=X&after=1.5","id=X&secret=PRIVATE_SENTINEL"])expect((await publicSearchGateway(request("/public/v1/products/search?"+query))).status).toBe(400);
  expect((await publicProductGateway(request("/public/v1/products/bad/routes"),"bad","routes")).status).toBe(400);expect((await publicProductGateway(request("/public/v1/products/"+batchId+"/quantity?after=0"),batchId,"quantity")).status).toBe(400);expect(spy).not.toHaveBeenCalled();
 });
 it("validates route pages and never treats page rows as global quantity totals",async()=>{const spy=vi.fn<typeof fetch>().mockResolvedValue(response(firstRoutePage));vi.stubGlobal("fetch",spy);const result=await publicProductGateway(request("/public/v1/products/"+batchId+"/routes?after=9007199254741000"),batchId,"routes");expect(result.status).toBe(200);expect(spy.mock.calls[0][0]).toContain("after=9007199254741000");spy.mockResolvedValue(response(firstRoutePage));expect((await publicProductGateway(request("/public/v1/products/"+batchId+"/routes?after=9007199254741010"),batchId,"routes")).status).toBe(502)});
 it("token-free discovery client keeps cancellation and publication gates",async()=>{const spy=vi.fn<typeof fetch>().mockResolvedValue(response(searchPage));const client=createPublicClient("",spy);expect((await client.search(batchQuantity.externalId)).products).toHaveLength(2);expect(spy.mock.calls[0][1]).toMatchObject({credentials:"omit",referrerPolicy:"no-referrer",method:"GET"});spy.mockResolvedValue(response({},404));await expect(client.routes(batchId)).rejects.toMatchObject({kind:"missing"});await expect(client.search("", "A")).rejects.toMatchObject({kind:"invalid"});});
 it("supports a code filter while the originating business withholds its display profile",()=>{const data={...searchPage,products:[{...searchPage.products[0],origin:{...searchPage.products[0].origin,name:null,businessCode:null}}]};expect(validatePage(searchSchema.parse(data),"0",50,"search",batchQuantity.externalId,"A").products[0].origin.name).toBeNull();});
 it("authenticated quantity writes use the exact source, quantity, version and text through the session gateway",async()=>{
  const spy=vi.fn<typeof fetch>().mockResolvedValue(response({sessionToken:token,expiresAt:new Date(Date.now()+1800000).toISOString(),user:operatorUser}));vi.stubGlobal("fetch",spy);
  const login=await operatorGateway(request("/operator/api/login",{email:operatorUser.email,password:"Synthetic-Only-Password-2026"}),"login");const cookie=login.headers.get("set-cookie")!.split(";")[0];
  const body={version:"9007199254741001",routeId:ownRoutes[0].id,quantity:500,reason:"Spoiled",reasonText:"Packaging damaged · বাংলাদেশ",confirmed:true,idempotencyKey:"removal-test-1234"};
  spy.mockResolvedValue(response({...writeResult,removedQuantity:"500",reason:"Spoiled",reasonText:body.reasonText}));const result=await operatorGateway(request("/operator/api/products/"+batchId+"/remove",body,cookie),"remove",batchId);expect(result.status).toBe(200);expect(spy.mock.calls.at(-1)?.[0]).toBe("https://api.example/operator/v1/products/"+batchId+"/remove");expect(JSON.parse(spy.mock.calls.at(-1)![1]!.body as string)).toEqual(body);
  for(const returned of [{...writeResult,removedQuantity:"499",reason:"Spoiled",reasonText:body.reasonText},{...writeResult,removedQuantity:"500",reason:"Lost",reasonText:body.reasonText},{...writeResult,removedQuantity:"500",reason:"Spoiled",reasonText:"Wrong explanation"}]){
   spy.mockResolvedValue(response(returned));expect((await operatorGateway(request("/operator/api/remove",body,cookie),"remove",batchId)).status).toBe(503);
  }
  const before=spy.mock.calls.length;expect((await operatorGateway(request("/operator/api/remove",{...body,organizationId:operatorUser.organizationId},cookie),"remove",batchId)).status).toBe(400);expect((await operatorGateway(request("/operator/api/remove",{...body,reasonText:""},cookie),"remove",batchId)).status).toBe(400);expect(spy.mock.calls.length).toBe(before);
  spy.mockResolvedValue(response({...writeResult,removedQuantity:"500",reason:"Spoiled",reasonText:body.reasonText,privateKey:"PRIVATE_SENTINEL"}));const rejected=await operatorGateway(request("/operator/api/remove",body,cookie),"remove",batchId);expect(rejected.status).toBe(503);expect(await rejected.text()).not.toContain("PRIVATE_SENTINEL");
 });
});
