import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import jsQR from "jsqr";
import { operatorUser, operatorProduct, operatorHistory, businessId } from "./operator-fixtures";
import { batchId, batchCode, batchQuantity, batchProduct, sourceRoutes, ownRoutes, firstRoutePage, batchPreview, writeResult, searchPage } from "./batch-fixtures";
const browserErrors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];browserErrors.set(page,errors);page.on("pageerror",error=>errors.push(error.message));});
test.afterEach(async({page})=>{expect(browserErrors.get(page)).toEqual([]);});
async function login(page:Page){
 await page.goto("/operator/sign-in");await page.getByLabel("Email address",{exact:true}).fill(operatorUser.email);await page.getByLabel("Password",{exact:true}).fill("Synthetic-Only-Password-2026");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page.locator("[data-operator-record]")).toBeVisible();
}
async function receivePreview(page:Page){await login(page);await page.goto("/operator/receive");await page.getByLabel("Tracking ID or product / batch ID",{exact:true}).fill(batchCode);await page.getByRole("button",{name:"Find product",exact:true}).click();await expect(page.getByRole("heading",{name:"Cola batch",exact:true})).toBeVisible();}
async function accessible(page:Page){expect((await new AxeBuilder({page}).withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test("registration keeps the business ID, toggles batch quantity, and prints the issued short code",async({page},info)=>{
 await page.route("**/operator/api/me",route=>route.fulfill({json:{user:{...operatorUser,businessCode:"A"}}}));await login(page);await page.goto("/operator/products/new");
 await page.getByLabel("Product name",{exact:true}).fill("Cola bottles");await page.getByLabel("Product / batch ID",{exact:true}).fill("BATCH-001");await expect(page.getByLabel("Product / batch ID",{exact:true})).toHaveValue("BATCH-001");
 await page.getByRole("button",{name:"Use business code in this ID",exact:true}).click();await expect(page.getByLabel("Product / batch ID",{exact:true})).toHaveValue("A / BATCH-001");
 await page.getByLabel("Batch product",{exact:true}).check();await page.getByLabel("Number of items",{exact:true}).fill("1000000");await page.getByLabel("Batch product",{exact:true}).uncheck();await expect(page.getByLabel("Number of items",{exact:true})).toHaveCount(0);await expect(page.getByText("Single product · 1 item",{exact:true})).toBeVisible();
 await page.getByLabel("Batch product",{exact:true}).check();await expect(page.getByLabel("Number of items",{exact:true})).toHaveValue("2");await page.getByLabel("Number of items",{exact:true}).fill("1000000");
 await accessible(page);const sent=page.waitForRequest(r=>r.url().endsWith("/products/create")&&r.method()==="POST");await page.getByRole("button",{name:"Add product",exact:true}).click();expect((await sent).postDataJSON()).toMatchObject({id:"A / BATCH-001",quantity:1000000});
 const qr=page.getByRole("img",{name:"Product tracking QR code",exact:true});await expect(qr).toBeVisible();const pixels=await qr.evaluate(e=>{const c=e as HTMLCanvasElement,i=c.getContext("2d")!.getImageData(0,0,c.width,c.height);return {width:i.width,height:i.height,data:Array.from(i.data)}});expect(jsQR(new Uint8ClampedArray(pixels.data),pixels.width,pixels.height)?.data).toBe("http://127.0.0.1:4178/s/abc123xyz789");await page.screenshot({path:info.outputPath("batch-registration.png"),fullPage:true});
});
test("pending registration freezes its payload and retries with the same key without printing a premature QR",async({page})=>{
 await login(page);await page.goto("/operator/products/new");await page.getByLabel("Product name",{exact:true}).fill("Pending batch");await page.getByLabel("Product / batch ID",{exact:true}).fill("B-009");
 const bodies:unknown[]=[];await page.route("**/operator/api/products/create",route=>{bodies.push(route.request().postDataJSON());return route.fulfill({json:{...writeResult,status:bodies.length===1?"BROADCAST":"CONFIRMED",shortCode:bodies.length===1?null:batchCode,blockNumber:bodies.length===1?null:"42"}})});
 await page.getByRole("button",{name:"Add product",exact:true}).click();await expect(page.getByRole("button",{name:"Check confirmation",exact:true})).toBeEnabled();await expect(page.getByLabel("Product / batch ID",{exact:true})).toBeDisabled();await expect(page.getByRole("img",{name:"Product tracking QR code",exact:true})).toHaveCount(0);
 await page.getByRole("button",{name:"Check confirmation",exact:true}).click();await expect(page.getByRole("img",{name:"Product tracking QR code",exact:true})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);
});
test("batch receipt selects an exact source across pages, prevents own-source and excess quantity, and preserves the version",async({page},info)=>{
 await receivePreview(page);await expect(page.getByText("899,300 out of 1,000,000 available",{exact:true})).toBeVisible();await expect(page.getByText("199,300 available",{exact:true})).toBeVisible();
 const own=page.locator(`#source-${ownRoutes[0].id}`);await expect(own).toBeDisabled();const receive=page.getByRole("button",{name:"Request to receive",exact:true});await expect(receive).toBeDisabled();await expect(page.locator('input[name="source-receipt"]:checked')).toHaveCount(0);
 await page.getByRole("button",{name:"Show more receipts",exact:true}).click();const cards=page.locator('.receipt-preview .selection-list li').filter({has:page.locator('.form-check-label').filter({hasText:/^Independent Distributor$/})});await expect(cards).toHaveCount(2);await expect(cards.nth(1)).toContainText("Repair Workshop");
 await page.locator(`#source-${sourceRoutes[1].id}`).check();await page.getByLabel("Number of items received",{exact:true}).fill("400001");await page.getByLabel("I have physically received this product",{exact:true}).check();await expect(receive).toBeDisabled();await expect(page.getByRole("alert").filter({hasText:"Enter a whole number"})).toContainText("400,000");
 await page.getByLabel("Number of items received",{exact:true}).fill("250");await expect(receive).toBeDisabled();await page.getByLabel("I have physically received this product",{exact:true}).check();await accessible(page);await page.screenshot({path:info.outputPath("batch-source-selection.png"),fullPage:true});
 const sent=page.waitForRequest(r=>r.url().endsWith("/receive")&&r.method()==="POST");await receive.click();const request=await sent;expect(request.postDataJSON()).toMatchObject({sourceRouteId:sourceRoutes[1].id,quantity:250,version:"9007199254741001",confirmed:true});expect(request.headers().authorization).toBeUndefined();await expect(page.getByRole("status").filter({hasText:"Awaiting the current owner"})).toBeVisible();await expect(receive).toHaveCount(0);
});
test("batch removal uses only an owned receipt, requires explanations, and keeps global totals separate",async({page},info)=>{
 await login(page);await page.goto("/operator/products/"+batchId);await expect(page.getByRole("heading",{name:"Cola batch",exact:true})).toBeVisible();await expect(page.getByText("899,300 out of 1,000,000 available",{exact:true})).toBeVisible();await expect(page.getByText("199,300 available",{exact:true})).toBeVisible();
 await expect(page.getByLabel("Your receipt",{exact:true})).toBeEnabled();await expect(page.getByLabel("Your receipt",{exact:true}).locator("option")).toHaveCount(2);await page.getByRole("button",{name:"Show more of your receipts",exact:true}).click();await expect(page.getByLabel("Your receipt",{exact:true}).locator("option")).toHaveCount(3);
 await page.getByLabel("Your receipt",{exact:true}).selectOption(ownRoutes[1].id);await page.getByLabel("Number of items to remove",{exact:true}).fill("100001");await page.getByLabel("I confirm these items should leave the supply chain",{exact:true}).check();const remove=page.getByRole("button",{name:"Remove from supply chain",exact:true});await expect(remove).toBeDisabled();
 await page.getByLabel("Number of items to remove",{exact:true}).fill("100000");await page.getByLabel("Reason",{exact:true}).selectOption("Spoiled");await page.getByLabel("I confirm these items should leave the supply chain",{exact:true}).check();await expect(remove).toBeDisabled();await page.getByLabel("Explanation",{exact:true}).fill("Packaging damaged during storage · বাংলাদেশ");await page.getByLabel("I confirm these items should leave the supply chain",{exact:true}).check();await accessible(page);await page.screenshot({path:info.outputPath("batch-removal.png"),fullPage:true});
 const sent=page.waitForRequest(r=>r.url().endsWith("/remove")&&r.method()==="POST");await remove.click();expect((await sent).postDataJSON()).toMatchObject({routeId:ownRoutes[1].id,quantity:100000,version:"9007199254741001",reason:"Spoiled",reasonText:"Packaging damaged during storage · বাংলাদেশ",confirmed:true});await expect(page.getByText("Confirmed. Product history will update shortly.",{exact:true})).toBeVisible();await expect(remove).toBeDisabled();await expect(page.locator(".operator-product-summary .supply-chain-status")).toHaveText("In supply chain");
 await expect(page.locator(".operator-timeline")).toContainText("500 items");await expect(page.locator(".operator-timeline")).toContainText("Broken packaging <b>plain text</b>");await expect(page.locator(".operator-timeline b")).toHaveCount(0);
});
test("public business-ID search handles duplicate products and shows consented holders and reason totals without writes",async({page,context},info)=>{
 await context.addCookies([{name:"tf_operator_dev",value:"synthetic-only",domain:"127.0.0.1",path:"/"}]);const calls:{path:string;method:string;cookie:boolean;auth:boolean}[]=[];page.on("request",r=>{const path=new URL(r.url()).pathname;if(path.startsWith("/public/")||path.startsWith("/operator/api/"))calls.push({path,method:r.method(),cookie:!!r.headers().cookie,auth:!!r.headers().authorization})});
 await page.goto("/");await page.getByLabel("Tracking ID or product / batch ID",{exact:true}).fill(batchQuantity.externalId);await page.getByRole("button",{name:"Track product",exact:true}).click();await expect(page.getByRole("button",{name:"Choose product",exact:true})).toHaveCount(2);await page.getByRole("button",{name:"Choose product",exact:true}).first().click();await expect(page).toHaveURL(new RegExp("/s/"+batchCode+"$"));
 await expect(page.getByText("899,300 out of 1,000,000 available",{exact:true})).toBeVisible();await expect(page.getByRole("region",{name:"Businesses holding this batch",exact:true})).toContainText("199,300 available · 2 receipts");await expect(page.locator(".reason-totals")).toContainText("Spoiled");await expect(page.locator(".reason-totals")).toContainText("500");await expect(page.getByLabel("Product availability")).not.toContainText("Your business");
 await page.getByRole("button",{name:"View available receipts",exact:true}).click();await page.getByRole("button",{name:"Show more receipts",exact:true}).click();await page.getByLabel("Receipt to inspect",{exact:true}).selectOption(sourceRoutes[1].id);await expect(page.getByRole("region",{name:"Available batch receipts",exact:true})).toContainText("From Repair Workshop");
 await expect(page.getByRole("button",{name:"Request to receive",exact:true})).toHaveCount(0);expect(calls.every(c=>c.method==="GET"&&!c.cookie&&!c.auth&&!c.path.startsWith("/operator/"))).toBe(true);await accessible(page);await page.screenshot({path:info.outputPath("public-batch-availability.png"),fullPage:true});
});
test("operator search filters the origin and resets the previous product when the query changes",async({page})=>{
 await login(page);await page.goto("/operator/receive");const field=page.getByLabel("Tracking ID or product / batch ID",{exact:true});await field.fill(batchQuantity.externalId);await page.getByText("Filter by originating business",{exact:true}).click();await page.getByLabel("Originating business code (optional)",{exact:true}).fill("a");await page.getByRole("button",{name:"Find product",exact:true}).click();await expect(page.getByRole("button",{name:"Choose product",exact:true})).toHaveCount(1);await page.getByRole("button",{name:"Choose product",exact:true}).click();await expect(page.locator(".receipt-preview")).toBeVisible();await field.fill("OTHER-ID");await expect(page.locator(".receipt-preview")).toHaveCount(0);await expect(page.locator('input[name="source-receipt"]')).toHaveCount(0);await page.getByRole("button",{name:"Find product",exact:true}).click();await expect(page.getByText("No matching products available to view.",{exact:true})).toBeVisible();
});
test("a new single uses whole-item removal with version and written reason without batch inputs",async({page})=>{
 const single={...operatorProduct,quantity:{...batchQuantity,externalId:"SERIAL-001",initialQuantity:"1",availableQuantity:"1",removedQuantity:"0",isBatch:false,inSupplyChain:true,ownAvailableQuantity:"1",reasons:batchQuantity.reasons.map(r=>({...r,quantity:"0"}))}};
 await page.route("**/operator/api/products/"+operatorProduct.id+"/history?*",route=>route.fulfill({json:{...operatorHistory,product:single}}));await page.route("**/operator/api/receive/"+operatorProduct.id,route=>route.fulfill({json:{trackingId:operatorProduct.id,name:single.name,holder:single.holder,closed:false,version:"7",canReceive:false,quantity:single.quantity}}));
 await login(page);await page.goto("/operator/products/"+operatorProduct.id);await expect(page.getByLabel("Reason",{exact:true})).toBeEnabled();await expect(page.getByLabel("Your receipt",{exact:true})).toHaveCount(0);await expect(page.getByLabel("Number of items to remove",{exact:true})).toHaveCount(0);await page.getByLabel("Reason",{exact:true}).selectOption("Other");await page.getByLabel("Explanation",{exact:true}).fill("Withdrawn by owner");await page.getByLabel("I confirm this product should leave the supply chain",{exact:true}).check();
 let payload:Record<string,unknown>={};await page.route("**/operator/api/products/"+operatorProduct.id+"/remove",route=>{payload=route.request().postDataJSON();return route.fulfill({json:{...writeResult,trackingId:operatorProduct.id,removedQuantity:"1",reason:"Other",reasonText:"Withdrawn by owner"}})});await page.getByRole("button",{name:"Remove from supply chain",exact:true}).click();await expect(page.getByText("Confirmed. Product history will update shortly.",{exact:true})).toBeVisible();expect(payload).toMatchObject({version:"7",reason:"Other",reasonText:"Withdrawn by owner",confirmed:true});expect(payload).not.toHaveProperty("routeId");expect(payload).not.toHaveProperty("quantity");
});
test("stale stock rejects a receipt and never silently resubmits using a new version",async({page})=>{
 await receivePreview(page);await page.locator(`#source-${sourceRoutes[0].id}`).check();await page.getByLabel("I have physically received this product",{exact:true}).check();let writes=0;await page.route("**/operator/api/products/"+batchId+"/receive",route=>{writes++;return route.fulfill({status:409,json:{error:{code:"operation_not_allowed"}}})});await page.getByRole("button",{name:"Request to receive",exact:true}).click();await expect(page.getByRole("status")).toContainText("Stock changed");await expect(page.getByRole("button",{name:"Check confirmation",exact:true})).toHaveCount(0);expect(writes).toBe(1);await page.getByRole("button",{name:"Receive another product",exact:true}).click();await expect(page.locator(".receipt-preview")).toHaveCount(0);
});

test("signup accepts an optional custom business code and reports its reservation",async({page})=>{
 await page.goto("/operator/sign-in");await page.getByRole("button",{name:"Register a business",exact:true}).click();await page.getByLabel("Your name",{exact:true}).fill("Demo Operator");await page.getByLabel("Business name",{exact:true}).fill("Independent Repair Business");const type=page.getByRole("combobox",{name:"Business type",exact:true});await type.fill("Repair workshop");await type.press("Enter");await page.getByLabel("Business code (optional)",{exact:true}).fill("REPAIR7");await page.getByLabel("Email address",{exact:true}).fill(operatorUser.email);await page.getByLabel("Password",{exact:true}).fill("Synthetic-Only-Password-2026");
 const sent=page.waitForRequest(r=>r.url().endsWith("/signup")&&r.method()==="POST");await page.getByRole("button",{name:"Register business",exact:true}).click();expect((await sent).postDataJSON()).toMatchObject({businessCode:"REPAIR7",businessType:"Repair workshop"});await expect(page.getByRole("status")).toContainText("Your business code is REPAIR7.");await expect(page.getByLabel("Password",{exact:true})).toHaveValue("");
});
test("an uncertain receipt request reuses its original source, amount, version and operation key",async({page})=>{
 await receivePreview(page);await page.locator(`#source-${sourceRoutes[0].id}`).check();await page.getByLabel("Number of items received",{exact:true}).fill("200");await page.getByLabel("I have physically received this product",{exact:true}).check();const bodies:unknown[]=[];
 await page.route("**/operator/api/products/"+batchId+"/receive",route=>{bodies.push(route.request().postDataJSON());return bodies.length===1?route.fulfill({status:503,json:{error:{code:'unavailable'}}}):route.fulfill({status:202,json:{...writeResult,receiptRequestId:'12345678-1234-4234-8234-123456789abc',status:'WAITING_APPROVAL',transactionHash:null,blockNumber:null,receivedRouteId:"0x"+"c1".repeat(32),quantity:"200"}})});
 await page.getByRole("button",{name:"Request to receive",exact:true}).click();await expect(page.getByLabel("Number of items received",{exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Check request",exact:true})).toBeEnabled();await page.getByRole("button",{name:"Check request",exact:true}).click();await expect(page.getByRole("status").filter({hasText:'Awaiting the current owner'})).toBeVisible();expect(bodies[1]).toEqual(bodies[0]);
});
test("publication revocation while paging holders hides the batch and its loaded names",async({page})=>{
 let revoked=false;await page.route("**/public/v1/products/"+batchId+"/holders?*",route=>{if(revoked)return route.fulfill({status:404,json:{}});return route.fulfill({json:{holders:[{id:businessId,name:"Previously shared name",availableQuantity:"199300",routeCount:2}],page:{hasMore:true,next:businessId}}})});
 await page.route("**/public/v1/short-links/"+batchCode,route=>revoked?route.fulfill({status:404,json:{}}):route.continue());await page.goto("/s/"+batchCode);await expect(page.getByText("Previously shared name",{exact:true})).toBeVisible();revoked=true;await page.getByRole("button",{name:"Show more businesses",exact:true}).click();await expect(page.locator("[data-public-record]")).toHaveCount(0);await expect(page.getByText("Previously shared name",{exact:true})).toHaveCount(0);
});
test("a revoked session on removal clears the private product and returns to sign-in",async({page})=>{
 await login(page);await page.goto("/operator/products/"+batchId);await expect(page.getByLabel("Your receipt",{exact:true})).toBeEnabled();await page.getByLabel("Your receipt",{exact:true}).selectOption(ownRoutes[0].id);await page.getByLabel("I confirm these items should leave the supply chain",{exact:true}).check();await page.route("**/operator/api/products/"+batchId+"/remove",route=>route.fulfill({status:401,json:{error:{code:"signed_out"}}}));await page.getByRole("button",{name:"Remove from supply chain",exact:true}).click();await expect(page).toHaveURL(/\/operator\/sign-in$/);await expect(page.locator("[data-operator-record]")).toHaveCount(0);
});
